const Map<String, String> br_BR = {
  "Sport live tv":  "Esporte TV ao Vivo",
  "Today Fixture":  "Ajuste de hoje",
  "Home":  "Início",
  "Match":  "Jogo",
  "Stream":  "Stream",
  "League":  "Liga",
  "Menu":  "Menu",
  "Match Details":  "Detalhes do Jogo",
  "Timeline":  "Linha do Tempo",
  "Statistics":  "Estatisticas",
  "Line Up":  "Line Up",
  "Head to head": "Head to head",
  "No data Found": "Nenhum dado encontrado",
  "Off":  "Off",
  "Live":  "Ao vivo",
  "Fixture":  "Acessório",
  "Recent":  "Recente",
  "Standing":  "Standing",
  "Top Score":  "Melhor Pontuação",
  "All":  "Todos",
  "Away":  "Fora",
  "Game":  "Jogo",
  "Substitutes":  "Substitutos",
  "Shots":  "Chutes",
  "Goals":  "Gols",
  "Passes":  "Passes",
  "Tackles":  "Tackles",
  "Dribbles":  "Drible",
  "Fouls":  "Faltas",
  "Cards":  "Cartões",
  "Penalty":  "Penalidade",
  "Live Stream":  "Transmissão ao Vivo",
  "All League":  "Todas as Ligas",
  "Search League":  "Procurar por Ligas",
  "About":  "Sobre",
  "Privacy Policy":  "Política de Privacidade",
  "Terms and Condition":  "Termos e Condições",
  "Telegram":  "Telegram",
  "Rate us":  "Nos avalie",
  "Feedback":  "Feedback",
   "Language": "Linguagem",
  
};