const Map<String, String> en_US = {
  "Sport live tv": "Sport live tv",
  "Today Fixture": "Today Fixture",
  "Home": "Home",
  "Match": "Match",
  "Stream": "Stream",
  "League": "League",
  "Menu": "Menu",
  "Match Details": "Match Details",
  "Timeline": "Timeline",
  "Statistics": "Statistics",
  "Line Up": "Line Up",
  "Head to headHead to hea": "",
  "No data FoundNo data Foun": "",
  "Off": "Off",
  "Live": "Live",
  "Fixture": "Fixture",
  "Recent": "Recent",
  "Standing": "Standing",
  "Top Score": "Top Score",
  "All": "All",
  "Away": "Away",
  "Game": "Game",
  "Substitutes": "Substitutes",
  "Shots": "Shots",
  "Goals": "Goals",
  "Passes": "Passes",
  "Tackles": "Tackles",
  "Dribbles": "Dribbles",
  "Fouls": "Fouls",
  "Cards": "Cards",
  "Penalty": "Penalty",
  "Live Stream": "Live Stream",
  "All League": "All League",
  "Search League": "Search League",
  "About": "About",
  "Privacy Policy": "Privecy Policy",
  "Terms and Condition": "Tearms and Condition",
  "Telegram": "Telegram",
  "Rate us": "Rate us",
  "Feedback": "Feedback",
  "Language": "Language",
};