const Map<String, String> kn_KH = {
  "Sport live tv": "ផ្សាយផ្ទាល់កីឡា",
  "Today Fixture": "ការប្រកួតថ្ងៃនេះ",
  "Home": "ម្ចាស់ផ្ទះ",
  "Match": "ប្រកួត",
  "Stream": "ស្រ្ទីម",
  "League": "លីគ",
  "Menu": "ម៉ឺនុយ",
  "Match Details": "លំអិត អំពីការប្រកួត",
  "Timeline": "ពេលវេលា",
  "Statistics": "ស្ថិតិ",
  "Line Up": "ឈ្មោះអ្នកចាប់ផ្តើម",
  "Head to head": "ស្ថិតិក្រុមទាំងពីរ",
  "No data Found": "គ្មានទិន្នន័យ",
  "Off": "បិទ",
  "Live": "ផ្សាយផ្ទាល់",
  "Fixture": "ការប្រកួត",
  "Recent": "ថ្មីៗ",
  "Standing": "តារាងពិន្ទុ",
  "Top Score": "គ្រាប់បាល់កំពូល",
  "All": "ទាំងអស់",
  "Away": "ភ្ញៀវ",
  "Game": "ហ្គេម",
  "Substitutes": "ផ្លាស់ប្ដូរកីឡាករ",
  "Shots": "ស៊ុត",
  "Goals": "គ្រាប់បាល់",
  "Passes": "ការបញ្ជូនបាល់",
  "Tackles": "ឈូស",
  "Dribbles": "ញាក់បាល់",
  "Fouls": "កំហុស",
  "Cards": "កាត",
  "Penalty": "ប៉េណាល់ទី",
  "Live Stream": "ការផ្សាយផ្ទាល់",
  "All League": "លីគទាំងអស់",
  "Search League": "ស្វែងរកលីគ",
  "About": "អំពី",
  "Privacy Policy": "គោលការណ៍ឯកជន",
  "Terms and Condition": "លក្ខខណ្ឌ",
  "Telegram": "តេឡេក្រាម",
  "Rate us": "វាយតម្លៃពួកយើង",
  "Feedback": "ការផ្តល់មតិ",
   "Language": "ភាសា",
};
