const Map<String, String> vi_VI = {
"Sport live tv": "Truyền hình trực tiếp Thể Thao",
"Today Fixture": "Lịch Thi Đấu Hôm Nay",
"Home": "Đội Nhà",
"Match": "Trận Đấu",
"Stream": "Trực tiếp",
"League": "Giải Đấu",
"Menu": "Mục lục",
"Match Details": "Chi Tiết Trận Đấu",
"Timeline": "Mốc Thời GIan",
"Statistics": "Phân Tích",
"Line Up": "Đội Hình",
"Head to headHead to hea": "Đối Đầu",
"No data FoundNo data Foun": "Không Tìm Thấy Dữ Liệu",
"Off": "Nghỉ",
"Live": "Trực Tiếp",
"Fixture": "Lịch",
"Recent": "Gần Đây",
"Standing": "Standing",
"Top Score":"gĐứng đầu bản",
"All": "Tất Cả",
"Away": "Đội Khách",
"Game": "Trận",
"Substitutes": "Dự Bị",
"Shots": "Đá",
"Goals": "Ghi Bàn",
"Passes": "Chuyền Bóng",
"Tackles": "Cản Phá",
"Dribbles": "Rê Bóng",
"Fouls": "Lỗi",
"Cards": "Thẻ",
"Penalty": "Đá Phạt",
"Live Stream": "Truyền hình trực tiếp",
"All League": "Tất Cả Giải",
"Search League": "Tìm Giải",
"About": "Về",
"Privacy Policy": "Chính Sách Bảo Mật",
"Terms and Condition": "Điều Khoản và Điều Kiện",
"Telegram": "Telegram",
"Rate us" : "iĐánh giá chúng tô",
"Feedback": "Phản Hồi",
 "Language": "Ngôn ngữ",

};