// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA26W8B40HypivwaLpKi1gmR0vliMSn3TM',
    appId: '1:1080534072165:web:939d46ee71f1dd9cde3f8c',
    messagingSenderId: '1080534072165',
    projectId: 'fover-7162e',
    authDomain: 'fover-7162e.firebaseapp.com',
    storageBucket: 'fover-7162e.firebasestorage.app',
    measurementId: 'G-Q4SCK4T205',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA65GbSRwhvfVaJ1jCLaTIv-jzPpZzh29s',
    appId: '1:1080534072165:android:a4aa6e2c51337facde3f8c',
    messagingSenderId: '1080534072165',
    projectId: 'fover-7162e',
    storageBucket: 'fover-7162e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZbqAJ_Qrp8-7bV5lT4mX1nZuPjFrm38Y',
    appId: '1:1080534072165:ios:f7f367f8aaa76ea0de3f8c',
    messagingSenderId: '1080534072165',
    projectId: 'fover-7162e',
    storageBucket: 'fover-7162e.firebasestorage.app',
    iosBundleId: 'com.example.footballXtLatest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZbqAJ_Qrp8-7bV5lT4mX1nZuPjFrm38Y',
    appId: '1:1080534072165:ios:f7f367f8aaa76ea0de3f8c',
    messagingSenderId: '1080534072165',
    projectId: 'fover-7162e',
    storageBucket: 'fover-7162e.firebasestorage.app',
    iosBundleId: 'com.example.footballXtLatest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA26W8B40HypivwaLpKi1gmR0vliMSn3TM',
    appId: '1:1080534072165:web:836d9024d907c137de3f8c',
    messagingSenderId: '1080534072165',
    projectId: 'fover-7162e',
    authDomain: 'fover-7162e.firebaseapp.com',
    storageBucket: 'fover-7162e.firebasestorage.app',
    measurementId: 'G-L5ZXL9HVWW',
  );
}
